;[
  {
    osrm_id: '56150805',
    specialties_en: [],
  },
  {
    osrm_id: '57931558',
    specialties_en: [
      'obstetrics_gynecology',
      'neonatology',
      'anesthesiology_intensive_care_pain_management',
    ],
  },
  {
    osrm_id: '923818393',
    specialties_en: ['emergency_medicine'],
  },
  {
    osrm_id: '72845361',
    specialties_en: [],
  },
  {
    osrm_id: '341277021',
    specialties_en: [],
  },
  {
    osrm_id: '1093062851',
    specialties_en: [
      'long_term_care',
      'palliative_care',
      'dementia_care',
      'physiotherapy_kinesitherapy',
      'psychology',
    ],
  },
  {
    osrm_id: '1315847144',
    specialties_en: ['emergency_medicine', 'pediatric_emergency_medicine'],
  },
  {
    osrm_id: '356742553',
    specialties_en: ['psychiatry', 'emergency_medicine', 'crisis_intervention_suicide_prevention'],
  },
  {
    osrm_id: '198691255',
    specialties_en: ['psychology', 'psychiatry', 'psychotherapy'],
  },
  {
    osrm_id: '630196432',
    specialties_en: ['internal_medicine', 'general_surgery', 'emergency_medicine'],
  },
  {
    osrm_id: '62041221',
    specialties_en: ['dentistry'],
  },
  {
    osrm_id: '4329133990',
    specialties_en: ['nursing_care', 'physical_medicine_rehabilitation'],
  },
  {
    osrm_id: '1093120683',
    specialties_en: ['nursing_care', 'long_term_care', 'emergency_medicine'],
  },
  {
    osrm_id: '5689598438',
    specialties_en: ['pediatric_emergency_medicine'],
  },
  {
    osrm_id: '5689598433',
    specialties_en: [],
  },
  {
    osrm_id: '28621227',
    specialties_en: [
      'ophthalmology',
      'obstetrics_gynecology',
      'allergology_clinical_immunology',
      'anesthesiology_intensive_care_pain_management',
      'otorhinolaryngology_ent',
      'general_surgery',
      'abdominal_surgery',
      'laboratory_medicine_clinical_pathology',
      'clinical_research',
      'dietetics_nutrition',
      'endocrinology',
      'aesthetic_laser_dermatology',
      'dermatology_dermatovenerology',
      'gastroenterology',
      'hematology',
      'infectious_diseases',
      'cardiology',
      'radiology_medical_imaging',
      'angiology_vascular_medicine',
      'mammology_breast_health',
      'nephrology',
      'neurology',
      'dentistry',
      'orthopedics_traumatology',
      'plastic_reconstructive_surgery',
      'preventive_medicine_health_screening',
      'psychiatry',
      'psychology',
      'pulmonology',
      'physical_medicine_rehabilitation',
      'sports_medicine',
      'rheumatology',
      'family_medicine',
      'emergency_medicine',
      'urology',
      'pediatrics_child_health',
    ],
  },
  {
    osrm_id: '60586888',
    specialties_en: [
      'family_medicine',
      'physical_medicine_rehabilitation',
      'radiology_medical_imaging',
      'laboratory_medicine_clinical_pathology',
      'dentistry',
      'dental_prosthetics',
      'psychiatry',
      'psychology',
      'occupational_medicine',
      'preventive_medicine_health_screening',
      'nursing_care',
      'long_term_care',
      'home_care_community_nursing',
      'palliative_care',
    ],
  },
  {
    osrm_id: '4317959291',
    specialties_en: [
      'addiction_medicine_treatment',
      'group_therapy',
      'psychology',
      'laboratory_medicine_clinical_pathology',
    ],
  },
  {
    osrm_id: '63106944',
    specialties_en: [
      'family_medicine',
      'obstetrics_gynecology',
      'pediatrics_child_health',
      'urology',
      'vaccinations_immunoprophylaxis',
      'otorhinolaryngology_ent',
      'radiology_medical_imaging',
      'dentistry',
      'preventive_medicine_health_screening',
      'oral_maxillofacial_surgery',
      'psychiatry',
      'psychology',
      'neurology',
      'massage_therapy',
      'laboratory_medicine_clinical_pathology',
    ],
  },
  {
    osrm_id: '37644427',
    specialties_en: [
      'physical_medicine_rehabilitation',
      'physiotherapy_kinesitherapy',
      'occupational_therapy',
      'speech_therapy',
      'hydrotherapy',
      'psychology',
      'social_work',
      'nursing_care',
      'massage_therapy',
    ],
  },
  {
    osrm_id: '200591271',
    specialties_en: [
      'obstetrics_gynecology',
      'perinatology_high_risk_pregnancy',
      'allergology_clinical_immunology',
      'otorhinolaryngology_ent',
      'dermatology_dermatovenerology',
      'laboratory_medicine_clinical_pathology',
      'radiology_medical_imaging',
      'dietetics_nutrition',
      'endocrinology',
      'gastroenterology',
      'genetics_medical',
      'longevity_medicine_anti_aging',
      'infectious_diseases',
      'cardiology',
      'physiotherapy_kinesitherapy',
      'vascular_surgery',
      'nephrology',
      'neurosurgery',
      'neurology',
      'fertility_treatment_reproductive_medicine',
      'ophthalmology',
      'orthopedics_traumatology',
      'pediatrics_child_health',
      'abdominal_surgery',
      'proctology',
      'plastic_reconstructive_surgery',
      'addiction_medicine_treatment',
      'psychiatry',
      'psychotherapy',
      'psychology',
      'pulmonology',
      'physical_medicine_rehabilitation',
      'rheumatology',
      'family_medicine',
      'preventive_medicine_health_screening',
      'toxicology',
      'urology',
      'internal_medicine',
      'stem_cell_banking_therapy',
    ],
  },
  {
    osrm_id: '238181090',
    specialties_en: [
      'family_medicine',
      'physical_medicine_rehabilitation',
      'radiology_medical_imaging',
      'laboratory_medicine_clinical_pathology',
      'dentistry',
      'dental_prosthetics',
      'psychiatry',
      'psychology',
      'occupational_medicine',
      'preventive_medicine_health_screening',
      'nursing_care',
      'long_term_care',
      'home_care_community_nursing',
      'palliative_care',
    ],
  },
  {
    osrm_id: '25892959',
    specialties_en: [
      'psychiatry',
      'child_adolescent_psychiatry',
      'addiction_medicine_treatment',
      'psychosocial_rehabilitation',
      'radiology_medical_imaging',
      'laboratory_medicine_clinical_pathology',
      'neuromodulation_therapies',
      'psychotherapy',
      'art_therapy',
      'speech_therapy',
      'crisis_intervention_suicide_prevention',
      'dementia_care',
    ],
  },
  {
    osrm_id: '1117319517',
    specialties_en: [
      'family_medicine',
      'pediatrics_child_health',
      'internal_medicine',
      'obstetrics_gynecology',
      'urology',
      'radiology_medical_imaging',
      'neurology',
      'dermatology_dermatovenerology',
      'general_surgery',
      'orthopedics_traumatology',
      'psychiatry',
      'psychotherapy',
      'preventive_medicine_health_screening',
      'dentistry',
      'cardiology',
    ],
  },
  {
    osrm_id: '4492021748',
    specialties_en: [
      'cardiology',
      'angiology_vascular_medicine',
      'rheumatology',
      'neurosurgery',
      'neurology',
      'abdominal_surgery',
      'endocrinology',
      'internal_medicine',
      'pulmonology',
      'allergology_clinical_immunology',
      'hematology',
      'oncology',
      'blood_banking_transfusion_medicine',
      'hepatology',
      'gastroenterology',
      'dietetics_nutrition',
      'pulmonary_hypertension_care',
      'radiology_medical_imaging',
      'nuclear_medicine',
      'cardiac_surgery',
      'thoracic_surgery',
      'otorhinolaryngology_ent',
      'ophthalmology',
      'infectious_diseases',
      'vascular_surgery',
      'genetics_medical',
      'nephrology',
      'urology',
      'physical_medicine_rehabilitation',
      'sports_medicine',
      'dermatology_dermatovenerology',
      'laboratory_medicine_clinical_pathology',
      'obstetrics_gynecology',
      'fertility_treatment_reproductive_medicine',
      'anesthesiology_intensive_care_pain_management',
      'plastic_reconstructive_surgery',
      'medical_informatics',
      'clinical_research',
      'clinical_pharmacology',
      'family_medicine',
      'diabetes_care_diabetology',
      'endoscopy',
      'general_surgery',
      'dialysis',
      'bone_marrow_transplantation',
      'molecular_medicine',
      'regenerative_medicine',
      'amyloidosis_care',
      'coagulation_disorders_hemophilia_care',
      'perinatology_high_risk_pregnancy',
      'neonatology',
    ],
  },
  {
    osrm_id: '64689950',
    specialties_en: [
      'physical_medicine_rehabilitation',
      'sports_medicine',
      'physiotherapy_kinesitherapy',
      'occupational_therapy',
    ],
  },
  {
    osrm_id: '230188665',
    specialties_en: ['veterinary_medicine'],
  },
  {
    osrm_id: '148498456',
    specialties_en: [
      'family_medicine',
      'internal_medicine',
      'pediatrics_child_health',
      'obstetrics_gynecology',
      'general_surgery',
      'dentistry',
      'neurology',
      'radiology_medical_imaging',
      'laboratory_medicine_clinical_pathology',
      'coagulation_disorders_hemophilia_care',
      'diabetes_care_diabetology',
      'preventive_medicine_health_screening',
      'oncology',
      'vaccinations_immunoprophylaxis',
      'pediatric_dentistry',
      'mammology_breast_health',
      'cardiology',
      'urology',
      'gastroenterology',
      'home_care_community_nursing',
      'nursing_care',
      'long_term_care',
    ],
  },
]
