;[
  { value: 'abdominal_surgery', label: 'Abdominal Surgery' },
  { value: 'addiction_medicine_treatment', label: 'Addiction Medicine / Treatment' },
  { value: 'aesthetic_laser_dermatology', label: 'Aesthetic / Laser Dermatology' },
  { value: 'allergology_clinical_immunology', label: 'Allergology and Clinical Immunology' },
  { value: 'amyloidosis_care', label: 'Amyloidosis Care' },
  {
    value: 'anesthesiology_intensive_care_pain_management',
    label: 'Anesthesiology, Intensive Care, and Pain Management',
  },
  { value: 'angiology_vascular_medicine', label: 'Angiology / Vascular Medicine' },
  { value: 'art_therapy', label: 'Art Therapy' },
  { value: 'blood_banking_transfusion_medicine', label: 'Blood Banking / Transfusion Medicine' },
  { value: 'bone_marrow_transplantation', label: 'Bone Marrow Transplantation' },
  { value: 'cardiac_surgery', label: 'Cardiac Surgery' },
  { value: 'cardiology', label: 'Cardiology' },
  { value: 'child_adolescent_psychiatry', label: 'Child and Adolescent Psychiatry' },
  { value: 'clinical_pharmacology', label: 'Clinical Pharmacology' },
  { value: 'clinical_research', label: 'Clinical Research' },
  {
    value: 'coagulation_disorders_hemophilia_care',
    label: 'Coagulation Disorders / Hemophilia Care',
  },
  {
    value: 'crisis_intervention_suicide_prevention',
    label: 'Crisis Intervention / Suicide Prevention',
  },
  { value: 'dementia_care', label: 'Dementia Care' },
  { value: 'dental_prosthetics', label: 'Dental Prosthetics' },
  { value: 'dentistry', label: 'Dentistry (General)' },
  { value: 'dermatology_dermatovenerology', label: 'Dermatology / Dermatovenerology' },
  { value: 'diabetes_care_diabetology', label: 'Diabetes Care / Diabetology' },
  { value: 'dialysis', label: 'Dialysis' },
  { value: 'dietetics_nutrition', label: 'Dietetics / Nutrition' },
  { value: 'emergency_medicine', label: 'Emergency Medicine' },
  { value: 'endocrinology', label: 'Endocrinology' },
  { value: 'endoscopy', label: 'Endoscopy' },
  { value: 'family_medicine', label: 'Family Medicine' },
  {
    value: 'fertility_treatment_reproductive_medicine',
    label: 'Fertility Treatment / Reproductive Medicine',
  },
  { value: 'gastroenterology', label: 'Gastroenterology' },
  { value: 'general_surgery', label: 'General Surgery' },
  { value: 'genetics_medical', label: 'Genetics (Medical)' },
  { value: 'geriatrics', label: 'Geriatrics' },
  { value: 'group_therapy', label: 'Group Therapy' },
  { value: 'hematology', label: 'Hematology' },
  { value: 'hepatology', label: 'Hepatology' },
  { value: 'home_care_community_nursing', label: 'Home Care / Community Nursing' },
  { value: 'hydrotherapy', label: 'Hydrotherapy' },
  { value: 'infectious_diseases', label: 'Infectious Diseases' },
  { value: 'internal_medicine', label: 'Internal Medicine' },
  {
    value: 'laboratory_medicine_clinical_pathology',
    label: 'Laboratory Medicine / Clinical Pathology',
  },
  { value: 'longevity_medicine_anti_aging', label: 'Longevity Medicine / Anti-Aging' },
  { value: 'long_term_care', label: 'Long-term Care' },
  { value: 'mammology_breast_health', label: 'Mammology / Breast Health' },
  { value: 'massage_therapy', label: 'Massage Therapy' },
  { value: 'medical_informatics', label: 'Medical Informatics' },
  { value: 'molecular_medicine', label: 'Molecular Medicine' },
  { value: 'neonatology', label: 'Neonatology' },
  { value: 'nephrology', label: 'Nephrology' },
  { value: 'neurology', label: 'Neurology' },
  { value: 'neuromodulation_therapies', label: 'Neuromodulation Therapies (TMS, ECT)' },
  { value: 'neurosurgery', label: 'Neurosurgery' },
  { value: 'nuclear_medicine', label: 'Nuclear Medicine' },
  { value: 'nursing_care', label: 'Nursing Care' },
  { value: 'obstetrics_gynecology', label: 'Obstetrics and Gynecology (OB/GYN)' },
  { value: 'occupational_medicine', label: 'Occupational Medicine' },
  { value: 'occupational_therapy', label: 'Occupational Therapy' },
  { value: 'oncology', label: 'Oncology (Medical, Chemotherapy, Radiation)' },
  { value: 'ophthalmology', label: 'Ophthalmology' },
  { value: 'oral_maxillofacial_surgery', label: 'Oral and Maxillofacial Surgery' },
  { value: 'orthopedics_traumatology', label: 'Orthopedics and Traumatology' },
  { value: 'otorhinolaryngology_ent', label: 'Otorhinolaryngology (ENT)' },
  { value: 'palliative_care', label: 'Palliative Care' },
  { value: 'pediatric_dentistry', label: 'Pediatric Dentistry' },
  { value: 'pediatric_emergency_medicine', label: 'Pediatric Emergency Medicine' },
  { value: 'pediatrics_child_health', label: 'Pediatrics / Child Health' },
  { value: 'perinatology_high_risk_pregnancy', label: 'Perinatology / High-Risk Pregnancy' },
  {
    value: 'physical_medicine_rehabilitation',
    label: 'Physical Medicine and Rehabilitation (PM&R)',
  },
  { value: 'physiotherapy_kinesitherapy', label: 'Physiotherapy / Kinesitherapy' },
  { value: 'plastic_reconstructive_surgery', label: 'Plastic and Reconstructive Surgery' },
  {
    value: 'preventive_medicine_health_screening',
    label: 'Preventive Medicine / Health Screening',
  },
  { value: 'proctology', label: 'Proctology' },
  { value: 'psychiatry', label: 'Psychiatry' },
  { value: 'psychology', label: 'Psychology' },
  { value: 'psychosocial_rehabilitation', label: 'Psychosocial Rehabilitation' },
  { value: 'psychotherapy', label: 'Psychotherapy' },
  { value: 'pulmonary_hypertension_care', label: 'Pulmonary Hypertension Care' },
  { value: 'pulmonology', label: 'Pulmonology' },
  {
    value: 'radiology_medical_imaging',
    label: 'Radiology / Medical Imaging (X-ray, CT, MRI, Ultrasound)',
  },
  { value: 'regenerative_medicine', label: 'Regenerative Medicine' },
  { value: 'rheumatology', label: 'Rheumatology' },
  { value: 'social_work', label: 'Social Work' },
  { value: 'speech_therapy', label: 'Speech Therapy' },
  { value: 'sports_medicine', label: 'Sports Medicine' },
  { value: 'stem_cell_banking_therapy', label: 'Stem Cell Banking / Therapy' },
  { value: 'thoracic_surgery', label: 'Thoracic Surgery' },
  { value: 'toxicology', label: 'Toxicology' },
  { value: 'urology', label: 'Urology' },
  { value: 'vaccinations_immunoprophylaxis', label: 'Vaccinations / Immunoprophylaxis' },
  { value: 'vascular_surgery', label: 'Vascular Surgery' },
  { value: 'veterinary_medicine', label: 'Veterinary Medicine' },
]
